apiVersion: v1
data:
  container-concurrency-target-default: "2"
  container-concurrency-target-percentage: "0.7"
  scale-to-zero-grace-period: 10s
  scale-to-zero-pod-retention-period: 0s
  stable-window: 10s
kind: ConfigMap
metadata:
  annotations:
  labels:
    serving.knative.dev/release: v0.16.0
  name: config-autoscaler
  namespace: knative-serving
